development:
  cloud_name: linareview
  api_key: '645711327949849'
  api_secret: vVoEVoy5MrhuHWHETvzdlb2bXAc
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: linareview
  api_key: '645711327949849'
  api_secret: vVoEVoy5MrhuHWHETvzdlb2bXAc
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: linareview
  api_key: '645711327949849'
  api_secret: vVoEVoy5MrhuHWHETvzdlb2bXAc
  enhance_image_tag: true
  static_file_support: false