default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.RAILS_DB_MAX_THREADS { 5 } %>
  host: <%= Rails.application.credentials.RAILS_DB_HOST %>

development:
  <<: *default
  database: metacritic_development
  username: postgres
  password: postgres

production:
  <<: *default
  database: metacritic_production
  username: postgres
  password: postgres
  #username: <%= Rails.application.credentials.production[:DATABASE_USER] %>
  #password: <%= Rails.application.credentials.production[:DATABASE_PASSWORD] %>